const animals = [
    {
        id: "01",
        url: "images/big-bird-eagle.jpeg",
        name: "eagle",
        type: "bird",
        size: "big",
    },
    {
        id: "02",
        url: "images/big-bird-peacock.jpeg",
        name: "peacock",
        type: "bird",
        size: "big",
    },
    {
        id: "03",
        url: "images/big-dog-german_dog.jpeg",
        name: "german_dog",
        type: "dog",
        size: "big",
    },
    {
        id: "04",
        url: "images/big-dog-hasky.jpeg",
        name: "hasky",
        type: "dog",
        size: "big",
    },
    {
        id: "05",
        url: "images/big-dog-shetland_heepdog5.jpg",
        name: "shetland_heepdog",
        type: "dog",
        size: "big",
    },
    {
        id: "06",
        url: "images/middle-bird-chicken.jpeg",
        name: "chicken",
        type: "bird",
        size: "middle",
    },
    {
        id: "07",
        url: "images/middle-bird-duck.jpeg",
        name: "duck",
        type: "bird",
        size: "middle",
    },
    {
        id: "08",
        url: "images/middle-dog-cockerspaniel.jpg",
        name: "cockerspaniel",
        type: "dog",
        size: "middle",
    },
    {
        id: "09",
        url: "images/middle-dog-french_bulldog-.jpg",
        name: "french_bulldog",
        type: "dog",
        size: "middle-dog",
    },
    {
        id: "010",
        url: "images/middle-dog-mops.jpg",
        name: "mops",
        type: "dog",
        size: "middle",
    },
    {
        id: "011",
        url: "images/small-bird-collibry.jpeg",
        name: "collibry",
        type: "bird",
        size: "small",
    },
    {
        id: "012",
        url: "images/small-bird-parrot.jpeg",
        name: "parrot",
        type: "bird",
        size: "small",
    },
    {
        id: "013",
        url: "images/small-dog-jack-russell.jpeg",
        name: "jack_russell",
        type: "dog",
        size: "small",
    },
    {
        id: "014",
        url: "images/small-dog-pincher.jpeg",
        name: "pincher",
        type: "dog",
        size: "small",
    },
    {
        id: "015",
        url: "images/small-dog-spitz.jpg",
        name: "spitz",
        type: "dog",
        size: "small",
    },
];

export default animals;
